version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysqlExpress
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
